### ISSUE TITLE
Command buttons are not working - no dbt command detected

### ISSUE THREAD

**Issue by alejandrorial** [ramonvermeulen/dbt-toolkit#139]
Pre-defined commands are not working, this is trying to compile the code 

![image](https://github.com/user-attachments/assets/4d09c244-40e5-4ca5-9f1b-32c92cd09229)

![image](https://github.com/user-attachments/assets/f56781d1-adb5-47b6-9ba5-22ac8c202a0f)

**Comment by ramonvermeulen** [comment]
@alejandrorial Thanks for submitting this bug! What dbt version are you using?

**Comment by ramonvermeulen** [comment]
@alejandrorial Reason I'm asking is because `--no-populate-cache` is introduced in version v1.5 of dbt: https://github.com/dbt-labs/docs.getdbt.com/commit/ac579e3de2d520034a80fedbb65d3c96b2fb0433, then I know this issue is related to the dbt version being used.

As of now I tested dbt-toolkit only on v1.7>

**Comment by ramonvermeulen** [comment]
Closed by https://github.com/ramonvermeulen/dbt-toolkit/pull/191
